language: dart

jobs:
  include:
    # LSIF Indexer CI Jobs
    - dart: stable
      name: "lsif_indexer (SDK: stable)"
      script:
        - ./tool/travis_quality.sh
        - ./tool/travis_tests.sh
    - dart: dev
      name: "LSIF indexer (SDK: dev)"
      script:
        - ./tool/travis_quality.sh
        - ./tool/travis_tests.sh
cache:
  directories:
   - $HOME/.pub-cache
   - $HOME/.dart_tool/build
