name: lsif_indexer
description: Generate an LSIF index (used by e.g. Sourcegraph) from Dart source files
version: 0.0.1
homepage: https://github.com/Workiva/lsif_indexer
authors:
 - Alan Knight <alan.knight@workiva.com>

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  analyzer: 0.41.1
  collection: ^1.14.13
  path: ^1.7.0
  package_config: ^1.9.3

dev_dependencies:
  pedantic: ^1.9.2
  test: ^1.15.7